# Site
name: "Ahy Consulting"
title: "Stories by Ahy Consulting"
description: "Some short stories of our day to day experiences at Ahy Consulting. News, Updates and much more."
logo: 'assets/images/ahyblacklogo.png'
favicon: 'assets/images/favicon.png'
footerlogo: 'assets/images/favicon.png'
baseurl:
google_analytics: 'UA-72482257-2'
disqus: 'storiesahyconsulting'
mailchimp-list: 'https://us11.admin.mailchimp.com/lists/members?id=426353'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  mona:
    name: Mona
    display_name: Mona
    gravatar: 1399f23088c67fe5fbae164f39a5d5c8
    email: info@ahyconsulting.com
    web: https://www.ahyconsulting.com
    twitter: https://twitter.com/ahyconsulting
    description: "Author of Ahy, Designer, UX Expert, Gamer, Cat Lover"
  harpreet:
    name: Harpreet
    display_name: Harpreet
    gravatar: 9112c8cc363a514e33024548f2b761ce
    email: harpreet@ahyconsulting.com
    web: https://www.ahyconsulting.com
    twitter: https://twitter.com/ahyharpreet
    description: "Author, Founder, Developer, Gamer, Dog Lover, Biker, Wanderer"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"
